# fly.toml app configuration file generated for unimatrix on 2026-07-02T02:51:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unimatrix'
primary_region = 'ams'

[build]
  builder = 'docker'
  dockerfile = 'Dockerfile.server'

[deploy]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[processes]
  app = 'node dist/index.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
